{{- if .Values.restore_job.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-bucket-uri-restore
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  POSTGRES_BUCKET_URI: {{ .Values.restore_job.bucket_uri | b64enc | quote }}
{{- end }}
