{{- if .Values.restore_job.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-postgres-restore
  annotations:
    {{ toYaml .Values.restore_job.annotations  | indent 4 }}
{{- end }}
