{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-bucket-uri
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  PGSQL_BUCKET_URI: {{ .Values.backup_job.bucket_uri | b64enc | quote }}
{{- end }}